name: quiz_mafortic
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

# DEPENDECY IMPOR FONT DARI GOOGLE FONTS
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # SECTION IMPOR ASSET BADGE DARI FOLDER 'ASSETS'
  assets:
    - assets/streak-badge.png

# Impor logo aplikasi dari folder aset
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
